repos:
  - repo: local
    hooks:
      - id: end-of-file-fixer
        name: fix end of files
        entry: python3 scripts/fix_end_of_file.py
        language: system
        types: [text]

      - id: trailing-whitespace
        name: trim trailing whitespace
        entry: python3 scripts/fix_trailing_whitespace.py
        language: system
        types: [text]

      - id: black
        name: black
        entry: python3 -m black
        language: system
        types_or: [python]

      - id: isort
        name: isort
        entry: python3 -m isort
        language: system
        types_or: [python]

      - id: ruff
        name: ruff
        entry: python3 -m ruff check --fix
        language: system
        types_or: [python]
